### ISSUE TITLE
wrong number of arguments: window-frame, 0

### ISSUE THREAD

**Issue by cnsgsz** [syohex/emacs-zoom-window#13]
I saw that error message when I use window-zoom-window. Any suggestions what I am missing?

**Comment by syohex** [comment]
Could you tell me in more detail ?
- How to reproduce ?
- Emacs version
- OS
- etc

**Comment by cnsgsz** [comment]
emacs 24.3.1, no special configuration (just installed through melpa as in the instruction), ubuntu14.04.

I don't know what's the special trigger to reproduce it because it happens at all times, e.g. whether I run emacs -nw under tmux, or just run emacs...

**Comment by syohex** [comment]
`window-frame` signature was changed at Emacs 24.4. Sorry I didn't test on Emacs 24.3. I have fixed this issue at #14. Please check latest version.
