### ISSUE TITLE
Unzoom changes point's column position

### ISSUE THREAD

**Issue by ivanbrennan** [syohex/emacs-zoom-window#15]
If I'm in the zoomed state, with point located mid-line, unzooming moves point to the beginning of the line.

Is this intentional? I can imagine it might be a simple way to ensure the point doesn't end up past the edge of an unzoomed window when restoring side-by-side split windows.

It would be nice if the point position remained unchanged when possible (e.g. when unzooming to a top-bottom split or when point wouldn't end up past the window edge anyway).

**Comment by syohex** [comment]
Thanks for reporting issue. I have sent PR(#16) for fixing this issue. Please check latest version.

**Comment by ivanbrennan** [comment]
Thanks!
