### ISSUE TITLE
suggestion: zoom-in the next buffer

### ISSUE THREAD

**Issue by deyaaeldeen** [syohex/emacs-zoom-window#4]
I think that we usually zoom out to go to another buffer, maybe the next one?
so I wonder if you can add another command, e.g. zoom-window-next, that, if called from zoom-in state, will zoom-in the next buffer in the original window.

**Comment by syohex** [comment]
How about #4 ? Is it right ?

**Comment by deyaaeldeen** [comment]
I was thinking of calling zoom-window-next in the current buffer while I am in zoom-in state to zoom in the next buffer without going back to the zoom-out state. However the behavior you have done may still be interesting too.

**Comment by syohex** [comment]
I have implemented at #12.
